name: compile-project

on: [push]

jobs:
  compile-project:
    runs-on: ubuntu-latest
    name: A job to compile diploma

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Download custom classes
        run: |
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost.cls'
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost/gost-diploma.sty'
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost/gost-headings.sty'
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost/gost-listings.sty'
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost/gost-lists.sty'
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost/gost-table.sty'
          curl -LO 'https://raw.githubusercontent.com/PlumpAlbert/dotfiles/master/texmf/tex/gost/gost-toc.sty'
      - name: Compile project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: nirs.tex
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./dotfiles/texmf/tex//:"
      - name: Release compiled file
        uses: softprops/action-gh-release@v1
        with:
          name: Diploma
          files: |
            nirs.pdf
