name: compile-project
on: [push]
jobs:
  compile-project:
    runs-on: ubuntu-latest
    container:
      image: plumpalbert/doctex
      env:
        SRC_DIR: /__w/diploma/diploma
        OUT_DIR: /__w/diploma/diploma/out
        TMP_DIR: /__w/_temp
        TEXLIVEFILE: nirs.tex

    steps:
      - uses: actions/checkout@v1
      - name: Compile document
        run: |
          work "xelatex nirs.tex"
