name: compile-project
on: [push]
jobs:
  compile-project:
    runs-on: ubuntu-latest
    container:
      image: plumpalbert/doctex
      env:
        TMP_DIR: /tmp
      volumes:
        - ${{ github.workspace }}:/work/src
        - ${{ github.workspace }}/build:/work/out

    steps:
      - uses: actions/checkout@v1
      - name: Compile document
        run: |
          cd /work/src
          work 'xelatex nirs.tex'
