name: compile-project

on: [push]

jobs:
  compile-project:
    runs-on: ubuntu-latest
    name: A job to compile diploma
    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Compile project
        uses: plumpalbert/doctex@v2
        with:
          root_file: nirs.tex
        env:
          SRC_DIR: /github/workspace
          BUILD_DIR: /github/workspace
      - name: Get compiled PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: nirs.pdf
      - name: Release compiled file
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: Diploma
          files: |
            nirs.pdf
