name: compile-project
on: [push]
jobs:
  compile-project:
    runs-on: ubuntu-latest
    container:
      image: plumpalbert/doctex
      volumes:
        - ${{ github.workspace }}:/work/src
        - ${{ github.workspace }}/out:/work/out

    steps:
      - uses: actions/checkout@v1
      - name: Compile document
        run: |
          work "xelatex nirs.tex"
