name: compile-project

on: [push]

jobs:
  compile-project:
    runs-on: ubuntu-latest
    name: A job to compile diploma

    steps:
      - name: Download custom classes
        uses: actions/checkout@v3
        with:
          repository: PlumpAlbert/dotfiles
          path: dotfiles
      - name: Clone repo
        uses: actions/checkout@v3
      - name: Compile project
        uses: xu-cheng/latex-action@v2
        with:
          root_file: nirs.tex
          latexmk_use_xelatex: true
        env:
          TEXINPUTS: ".:./dotfiles/texmf/tex//:"
      - name: Release compiled file
        uses: softprops/action-gh-release@v1
        with:
          name: Diploma
          files: |
            nirs.pdf
